### ISSUE TITLE
LowPower.h source

### ISSUE THREAD

**Issue by Elwell** [ReiniervdL/Vinduino#2]
Hi Reinier,

In the arduino sketches, you #include "LowPower.h" that isn't in the tree.

Is this from https://github.com/rocketscream/Low-Power, described in http://www.rocketscream.com/blog/2011/07/04/lightweight-low-power-arduino-library/ ?

**Comment by ReiniervdL** [comment]
Hi Andy, 
Correct, Vinduino uses the rocketscream low power library
