### ISSUE TITLE
Negative values of resistance, Soil moisture always zero!

### ISSUE THREAD

**Issue by aniket5941** [ReiniervdL/Vinduino#3]
I'm using Vinduino-H_V3.1 code, soil moisture always shows **zero** for **WET** and **DRY** and resistance is always **NEGATIVE** I done connection according picture attached, but I'm using **4700 ohm resistance** help me what I'm doing wrong, I have attached images of connection and readings, first reading image is of wet and second is for dry.
![capture1](https://cloud.githubusercontent.com/assets/28697966/26091869/8be9bb62-3a2b-11e7-8334-3874cce2d698.PNG)
![wet](https://cloud.githubusercontent.com/assets/28697966/26091873/95685f9a-3a2b-11e7-9c15-b5eb926f8cb6.PNG)
![capture](https://cloud.githubusercontent.com/assets/28697966/26091924/c8a2c256-3a2b-11e7-8a77-c4ffb6635085.PNG)

**Comment by ReiniervdL** [comment]
The code for the handheld was written for Arduino Pro Mini pin assignments.
What model of Arduino are you using?

**Comment by aniket5941** [comment]
Arduino pro mini 3.3v model

**Comment by ReiniervdL** [comment]
First question, do you have test equipment: multimeter, oscilloscope?

The code was written for the 5V version of the Arduino pro mini.
For 3.3V, I recommend removing the diodes, as they take away 0.6V from the voltage divider supply.
Next you need to program the outputs to high impedance when not used as output.
You can copy the code from the Vinduino R3 on Github for this.

Last but not least, double check your wiring.

**Comment by aniket5941** [comment]
No I'm not using any test equipment: multimeter, oscilloscope.
I tried Vinduino R3 on **Arduino UNO** but the same problem occurs.

**Comment by ReiniervdL** [comment]
I'd like to help with debugging if you provide me basic measurement data.  A $10 digital multimeter will go a long way get getting insight in what's going on. If you want to skip fault finding,  use the PCB design for the handheld reader, available here:
https://oshpark.com/shared_projects/QWzdU5S6

**Comment by aniket5941** [comment]
Thank you very much ,
I have DMM and my is circuit on bread board, I'm in little hurry so pcb would take time, so how should I proceed what data would you like to have from me.

**Comment by ReiniervdL** [comment]
Can you first check the power supply voltage?
Next, can you modify the “Blink” example program (in the Arduino IDE) to check that the two outputs driving the diodes are toggling.
Make the delay long, so your DMM can track the changing states.

**Comment by warriorfenixSM** [comment]
This values is with 22k in WM1:

WM1: 298552,2
WM1: 8670,15
WM1: 201160,2
WM1: 8706,15
WM1: 297079,2
WM1: 8409,15
WM1: 284256,2
WM1: 7925,15
WM1: 291596,2
WM1: 8521,15
WM1: 322377,2
WM1: 7823,15
WM1: 183822,2
