### ISSUE TITLE
USB serial crash using ftdi

### ISSUE THREAD

**Issue by pandrews255** [ReiniervdL/Vinduino#4]
I'm using the Vinduino R3 with the 2nd LM-210 wired into the Raspberry Pi.  After a random amount of time (minutes but rairly to hours) the USB serial crashes out and forces a reboot/re-plug of the usb ftdi in order to work again.  Easiest way to see this error is through:

`dmesg -T`
with the result:
`Nov 4 14:23:13 localhost kernel: [11761.350820] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32 `
(Note: this was not my exact error, but was close enough and how I found my solution.)

Solution:[https://github.com/raspberrypi/linux/issues/1187](url)

> You could try the nuclear option - add dwc_otg.speed=1 to /boot/cmdline.txt - this forces the entire bus to USB1.1 speeds. If you still get disconnects after that, then it's probably safe to say that the Pi isn't the issue.

This fixed my issue, though it seems a bit inelegant.  I don't need any high speed USB devices on the pi, so it seems effective.

No real question here, just posting for posterity.  Perhaps best in a Wiki format, but didn't see any other wiki pages.  If a more elegant solution exists, I'd be willing to try it.

**Comment by ReiniervdL** [comment]
Thanks!!
