### ISSUE TITLE
Bill of Materials for Vinduino R3

### ISSUE THREAD

**Issue by Bigben83** [ReiniervdL/Vinduino#6]
I cant seem to see a BOM list for the parts used on the R3
can you point me in the right direction please :-)

**Comment by Bigben83** [comment]
I have done a list up from the Schematic, there is a few holes to fill though.
https://docs.google.com/spreadsheets/d/1UatllHvDW_FJPWLYLjqeTI9wG5EkYtphUCcHgDXFkBM/edit?usp=sharing

**Comment by Bigben83** [comment]
Hello @ReiniervdL can you please tell me what the Diodes are D2-D5  are they a "9A1" 9.1V 0.3W zener?

**Comment by DanC6312** [comment]
Hi @Bigben83, Did you manage to figure this question out?

**Comment by Bigben83** [comment]
Hi @DanChippps no I didn't, I gather this is no longer maintained opensource hardware/software. 
I have built several of these units. I will have a look and see what I actually used.

**Comment by ReiniervdL** [comment]
The BOM has been added
