### ISSUE TITLE
Soil Moisutre Measure not works!

### ISSUE THREAD

**Issue by warriorfenixSM** [ReiniervdL/Vinduino#7]
Hi, i try works your source code: Vinduino-H_V3.1.ino with only one watermark connect to Arduino M0. But it doesn't work. I see the signal in the oscilloscope, but the code no changes values

![image](https://user-images.githubusercontent.com/30696031/37373679-e8a0bfb6-2717-11e8-9785-32af35288c63.png)

![da7f76b8-0d00-459a-829e-46f0b3962f8c](https://user-images.githubusercontent.com/30696031/37373732-20582e58-2718-11e8-9b6a-40d352c85254.jpg)

And this mi code:

#include <math.h>

#define NUM_READS 11    // Number of sensor reads for filtering

typedef struct {        // Structure to be used in percentage and resistance values matrix to be filtered (have to be in pairs)
  int moisture;
  long resistance;
  double tension;
} values;

const long knownResistor = 4700;  // Constant value of known resistor in Ohms

int activeDigitalPin = 11;         // 6 or 7 interchangeably
int supplyVoltageAnalogPin;       // 6-ON: A0, 7-ON: A1
int sensorVoltageAnalogPin;       // 6-ON: A1, 7-ON: A0

int supplyVoltage;                // Measured supply voltage
int sensorVoltage;                // Measured sensor voltage

values valueOf[NUM_READS];        // Calculated moisture percentages and resistances to be sorted and filtered

int i;                            // Simple index variable

void setup() {
  // initialize serial communications at 9600 bps:
  
  SerialUSB.begin(9600);
analogReadResolution(12);
  // initialize the digital pin as an output.
  // Pin 6 is sense resistor voltage supply 1
  pinMode(11, OUTPUT);    

  // initialize the digital pin as an output.
  // Pin 7 is sense resistor voltage supply 2
  pinMode(13, OUTPUT);   
}

void loop() {

      bemoticCore.ON_SENS();
  for (i=0; i<NUM_READS; i++) {

    setupCurrentPath();      // Prepare the digital and analog pin values

    // Read 1 pair of voltage values
    digitalWrite(activeDigitalPin, HIGH);                 // set the voltage supply on
    delay(10);
    supplyVoltage = analogRead(supplyVoltageAnalogPin);   // read the supply voltage
    SerialUSB.print("SV:");
    SerialUSB.println(supplyVoltage);
    sensorVoltage = analogRead(sensorVoltageAnalogPin);   // read the sensor voltage
    SerialUSB.print("SV:");
    SerialUSB.println(sensorVoltage);    
    digitalWrite(activeDigitalPin, LOW);                  // set the voltage supply off  
    delay(10); 

    // Calculate resistance and moisture percentage without overshooting 100
    // the 0.5 add-term is used to round to the nearest integer
    // Tip: no need to transform 0-1023 voltage value to 0-5 range, due to following fraction
    valueOf[i].resistance = long( float(knownResistor) * ( supplyVoltage - sensorVoltage ) / sensorVoltage + 0.5 );
    valueOf[i].moisture = min( int( pow( valueOf[i].resistance/31.65 , 1.0/-1.695 ) * 400 + 0.5 ) , 100 );
//    valueOf[i].tension = round( -20 * (double(valueOf[i].resistance)/1000) * ( 1 - 0.55)); // Watermark 0 < 1 kOhm
    valueOf[i].tension = round( ( -3.213 * (double(valueOf[i].resistance)/1000) - 4.093) / ( 1 - 0.009733 * (double(valueOf[i].resistance)/1000) - 0.01205*24)); // Watermark 1 < 8 kOhm
//    valueOf[i].tension = round(-2.246 - (5.239 * (double(valueOf[i].resistance)/1000)) - 0.06756 * pow(valueOf[i].resistance/1000,2)); // Watermark > 8 kOhm
//  valueOf[i].moisture = min( int( pow( valueOf[i].resistance/331.55 , 1.0/-1.695 ) * 100 + 0.5 ) , 100 );

  }
      sortMoistures(); 
         
      // Print out median values
      SerialUSB.print("SV: ");
      SerialUSB.println(supplyVoltage);
      SerialUSB.print("Se: ");
      SerialUSB.println(sensorVoltage);        
      SerialUSB.print("Resistencia Sensor: ");
      SerialUSB.println(valueOf[NUM_READS/2].resistance);
      SerialUSB.print("Moisture Sensor: ");
      SerialUSB.println(valueOf[NUM_READS/2].moisture);
      SerialUSB.print("Tension Sensor: ");
      SerialUSB.print(valueOf[NUM_READS/2].tension);
      SerialUSB.println(" kPa");
      delay(3000);

}

void setupCurrentPath() {
  if ( activeDigitalPin == 11 ) {
    activeDigitalPin = 13;
    supplyVoltageAnalogPin = A2;
    sensorVoltageAnalogPin = A0;
  }
  else {
    activeDigitalPin = 11;
    supplyVoltageAnalogPin = A0;
    sensorVoltageAnalogPin = A2;
  }
}

// Selection sort algorithm
void sortMoistures() {
  int j;
  values temp;
  for(i=0; i<NUM_READS-1; i++)
    for(j=i+1; j<NUM_READS; j++)
      if ( valueOf[i].moisture > valueOf[j].moisture ) {
        temp = valueOf[i];
        valueOf[i] = valueOf[j];
        valueOf[j] = temp;
      }
}

**Comment by ReiniervdL** [comment]
The Vinduino-H code is for a handheld reader, works for one sensor only.

Can you describe your setup?
Are you using the Vinduino handheld PCB? 
Does the code compile?

**Comment by warriorfenixSM** [comment]
I try to use the Vinduino handheld PCB and i have connect only sensors. I try use your code in a samd21 board
But the measures not's works

**Comment by ReiniervdL** [comment]
I have no experience with the SAMD21 board.
The operating principle is measuring a voltage in a voltage divider, where one of the resistors is the sensor, and the other resistor is your reference.
You should check correct wiring first and then look at the ADC measurements. Also make sure that the Watermark sensor is wetted, a dry sensor is infinite impedance.

**Comment by warriorfenixSM** [comment]
Hi Reinier,

Thanks for your answers. I have now different meassures but i don't understand the results Could you give me a hand?.

In WM1 i have connect a Irrometer sensor (Dry).
In WM2 and Wm3 i have nothing.

![image](https://user-images.githubusercontent.com/30696031/40021417-0a381588-57c5-11e8-8949-b39b6fef7ecc.png)

**Comment by ReiniervdL** [comment]
A dry watermark sensor is basically an open circuit.
You may want to check your circuit first with known resistor values connected to the sensor inputs.

**Comment by warriorfenixSM** [comment]
This values is with 22k in WM1:

WM1: 298552,2
WM1: 8670,15
WM1: 201160,2
WM1: 8706,15
WM1: 297079,2
WM1: 8409,15
WM1: 284256,2
WM1: 7925,15
WM1: 291596,2
WM1: 8521,15
WM1: 322377,2
WM1: 7823,15
WM1: 183822,2

Part of Code:

SerialUSB.print("WM1: ");
SerialUSB.print(valueOf[NUM_READS/2].resistance);
SerialUSB.print(",");
SerialUSB.print(valueOf[NUM_READS/2].moisture);
SerialUSB.println ();

Thanks so much!

**Comment by ReiniervdL** [comment]
The SerialUSB.print(valueOf[NUM_READS/2].resistance should show a value of 22k.
I cannot tell you remotely why it does not work.

First thing to try is program the unit to provide static state DC to the interface voltage divider.
Use a volt meter to measure the voltage and compare with the ADC input reading.

Best,

-Reinier-

**Comment by warriorfenixSM** [comment]
Hi, i fix now the board, the problem is in my pcb. 

Thanks for you support!
