### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by ShinyEdu** [ReiniervdL/Vinduino#8]
Sample code inludes a library LowPower.h but I can't find any libraries that match that name.

```
H:\Outbox\Vinduino-20180719T042419Z-001\Vinduino\Vinduino-R3_Wifi\VR3-WiFi-sample_code\Vinduino-R_Wifi_V1.0.ino:20:49: fatal error: LowPower.h: No such file or directory

 #include "LowPower.h"   // Needed for sleep mode

                                                 ^

compilation terminated.

exit status 1
Error compiling for board Arduino Pro or Pro Mini.
```

**Comment by ReiniervdL** [comment]
https://github.com/rocketscream/Low-Power

**Comment by ShinyEdu** [comment]
There are many other libraries missing, do you have a list of all additional libraries required?

**Comment by ReiniervdL** [comment]
The list of the libraries is in the code. You can easily find them if you Google....
